CREATE TABLE IF NOT EXISTS app_user (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) DEFAULT NULL,
  email varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  role varchar(255) CHECK (role IN ('STUDENT','ADMIN')) DEFAULT NULL,
  username varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_user_email UNIQUE (email),
  CONSTRAINT uk_user_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS exam (
  exam_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  duration int DEFAULT NULL,
  exam_name varchar(255) DEFAULT NULL,
  exam_type varchar(255) CHECK (exam_type IN ('JEE','NEET','CUSTOM')) DEFAULT NULL,
  question_paper_path varchar(255) DEFAULT NULL,
  status varchar(255) CHECK (status IN ('UPLOADED','PROCESSING','DRAFT','READY','FAILED')) DEFAULT NULL,
  PRIMARY KEY (exam_id)
);

CREATE TABLE IF NOT EXISTS practice_sessions (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp(6) DEFAULT NULL,
  extraction_verified boolean DEFAULT NULL,
  file_size_in_bytes bigint DEFAULT NULL,
  original_pdf_name varchar(255) DEFAULT NULL,
  processing_job_id varchar(255) DEFAULT NULL,
  processing_time_seconds double precision DEFAULT NULL,
  status varchar(255) CHECK (status IN ('UPLOADING','EXTRACTING','READY','IN_PROGRESS','COMPLETED','FAILED')) DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  total_questions int NOT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  upload_type varchar(255) CHECK (upload_type IN ('QUESTION_WITH_ANSWER','QUESTION_AND_SEPARATE_ANSWER_KEY','PDF_MOCK','PRACTICE_PAPER')) DEFAULT NULL,
  user_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_ps_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS practice_questions (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  correct_answer varchar(255) DEFAULT NULL,
  explanation varchar(5000) DEFAULT NULL,
  optiona varchar(1000) DEFAULT NULL,
  optionb varchar(1000) DEFAULT NULL,
  optionc varchar(1000) DEFAULT NULL,
  optiond varchar(1000) DEFAULT NULL,
  question varchar(5000) DEFAULT NULL,
  question_number int NOT NULL,
  practice_session_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_pq_session FOREIGN KEY (practice_session_id) REFERENCES practice_sessions (id)
);

CREATE TABLE IF NOT EXISTS mock_test_sessions (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  duration_seconds int DEFAULT NULL,
  score double precision DEFAULT NULL,
  started_at timestamp(6) DEFAULT NULL,
  completed_at timestamp(6) DEFAULT NULL,
  status varchar(255) CHECK (status IN ('ACTIVE','COMPLETED','TERMINATED')) DEFAULT NULL,
  total_questions int DEFAULT NULL,
  practice_session_id bigint NOT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_mts_session FOREIGN KEY (practice_session_id) REFERENCES practice_sessions (id),
  CONSTRAINT fk_mts_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS mock_test_answers (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  is_marked_for_review boolean DEFAULT NULL,
  is_skipped boolean DEFAULT NULL,
  selected_option varchar(255) DEFAULT NULL,
  time_spent_seconds bigint DEFAULT NULL,
  mock_test_session_id bigint NOT NULL,
  practice_question_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_mta_session FOREIGN KEY (mock_test_session_id) REFERENCES mock_test_sessions (id),
  CONSTRAINT fk_mta_question FOREIGN KEY (practice_question_id) REFERENCES practice_questions (id)
);

CREATE TABLE IF NOT EXISTS mock_test_results (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  accuracy double precision NOT NULL,
  correct_answers int NOT NULL,
  max_score double precision NOT NULL,
  percentage double precision NOT NULL,
  score double precision NOT NULL,
  skipped_questions int NOT NULL,
  submitted_at timestamp(6) DEFAULT NULL,
  time_taken_seconds bigint NOT NULL,
  wrong_answers int NOT NULL,
  mock_test_session_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_mtr_session UNIQUE (mock_test_session_id),
  CONSTRAINT fk_mtr_session FOREIGN KEY (mock_test_session_id) REFERENCES mock_test_sessions (id)
);

CREATE TABLE IF NOT EXISTS mock_test_subject_results (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  correct_answers int NOT NULL,
  score double precision NOT NULL,
  skipped_questions int NOT NULL,
  subject varchar(255) DEFAULT NULL,
  wrong_answers int NOT NULL,
  mock_test_session_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_mtsr_session FOREIGN KEY (mock_test_session_id) REFERENCES mock_test_sessions (id)
);

CREATE TABLE IF NOT EXISTS mock_test_difficulty_results (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  correct_answers int NOT NULL,
  difficulty_level varchar(255) DEFAULT NULL,
  score double precision NOT NULL,
  skipped_questions int NOT NULL,
  wrong_answers int NOT NULL,
  mock_test_session_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_mtdr_session FOREIGN KEY (mock_test_session_id) REFERENCES mock_test_sessions (id)
);

CREATE TABLE IF NOT EXISTS question (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  question varchar(255) DEFAULT NULL,
  subject varchar(255) DEFAULT NULL,
  correct_answer varchar(255) DEFAULT NULL,
  difficulty_level varchar(255) CHECK (difficulty_level IN ('EASY','MEDIUM','HARD')) DEFAULT NULL,
  marks int DEFAULT NULL,
  negative_marks double precision DEFAULT NULL,
  optiona varchar(255) DEFAULT NULL,
  optionb varchar(255) DEFAULT NULL,
  optionc varchar(255) DEFAULT NULL,
  optiond varchar(255) DEFAULT NULL,
  question_text varchar(5000) DEFAULT NULL,
  topic varchar(255) DEFAULT NULL,
  exam_id bigint DEFAULT NULL,
  question_number int DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_q_exam FOREIGN KEY (exam_id) REFERENCES exam (exam_id)
);

CREATE TABLE IF NOT EXISTS result (
  result_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  correct_answers int DEFAULT NULL,
  exam_id bigint DEFAULT NULL,
  score double precision DEFAULT NULL,
  student_name varchar(255) DEFAULT NULL,
  submitted_at timestamp(6) DEFAULT NULL,
  total_questions int DEFAULT NULL,
  wrong_answers int DEFAULT NULL,
  user_id bigint DEFAULT NULL,
  PRIMARY KEY (result_id),
  CONSTRAINT fk_r_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS test_session (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  correct_answers int NOT NULL,
  started_at timestamp(6) DEFAULT NULL,
  total_questions int NOT NULL,
  wrong_answers int NOT NULL,
  completed_at timestamp(6) DEFAULT NULL,
  score double precision NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS test_result (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  correct_answers int NOT NULL,
  performance varchar(255) DEFAULT NULL,
  subject varchar(255) DEFAULT NULL,
  wrong_answers int NOT NULL,
  user_id bigint DEFAULT NULL,
  score double precision NOT NULL,
  test_session_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_tr_session FOREIGN KEY (test_session_id) REFERENCES test_session (id),
  CONSTRAINT fk_tr_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
