import { useState, useEffect } from "react";
import { getSessions } from "../services/practiceService";
import { Link } from "react-router-dom";
import { FileText, Eye, Inbox } from "lucide-react";
import Button from "../components/ui/Button";
import Card from "../components/ui/Card";
import LoadingSpinner from "../components/common/LoadingSpinner";
import { formatDate } from "../utils/formatters";

function PracticePapers() {
  const [loading, setLoading] = useState(true);
  const [sessions, setSessions] = useState([]);

  useEffect(() => {
    async function loadSessions() {
      try {
        const response = await getSessions(0, 50);
        setSessions(response.content || []);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadSessions();
  }, []);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <LoadingSpinner size="lg" />
      </div>
    );
  }

  const readySessions = sessions.filter((s) => s.status === "READY");

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold tracking-tight font-outfit">Practice Papers & Solutions</h2>
        <p className="text-muted text-sm mt-1">
          Review step-by-step solved explanations generated by Google Gemini.
        </p>
      </div>

      {readySessions.length === 0 ? (
        <Card className="flex flex-col items-center justify-center p-12 text-center border-border">
          <Inbox size={48} className="text-muted mb-4 animate-bounce" />
          <h4 className="text-lg font-bold">No Solved Papers Available</h4>
          <p className="text-muted text-sm mt-1 max-w-sm">
            Go to the Workspace Dashboard to upload your first exam PDF. Once processed, solutions will appear here.
          </p>
          <Link to="/student/workspace" className="mt-6">
            <Button variant="primary">Go to Dashboard</Button>
          </Link>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {readySessions.map((session) => (
            <Card key={session.id} className="p-5 border border-border flex flex-col justify-between hover:border-primary/40 hover:shadow-lg transition-all duration-300">
              <div>
                <div className="flex items-center space-x-2.5 text-primary mb-3">
                  <FileText size={20} />
                  <span className="font-semibold text-xs bg-slate-800 text-muted px-2 py-0.5 rounded border border-border">
                    {session.totalQuestions} Questions
                  </span>
                </div>
                <h4 className="text-base font-bold text-text line-clamp-2 mb-2 font-outfit">
                  {session.title}
                </h4>
                <p className="text-muted text-xs font-mono">
                  Processed on {formatDate(session.createdAt)}
                </p>
              </div>

              <div className="mt-6">
                <Link to={`/student/practice/${session.id}/review`}>
                  <Button variant="outline" className="w-full flex items-center justify-center gap-1.5 border-border hover:bg-slate-800">
                    <Eye size={14} />
                    <span>Review Solutions</span>
                  </Button>
                </Link>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

export default PracticePapers;
