import { Routes, Route } from "react-router-dom";

import Home from "./pages/Home";
import Login from "./pages/Login";
import Register from "./pages/Register";
import Dashboard from "./pages/Dashboard";
import ProtectedRoute from "./components/common/ProtectedRoute";
import PublicRoute from "./components/common/PublicRoute";
import GuestLayout from "./components/layout/GuestLayout";
import StudentLayout from "./components/layout/StudentLayout";
import PlaceholderPage from "./pages/placeholder/PlaceholderPage";
import Workspace404 from "./pages/placeholder/Workspace404";
import { FileText, GraduationCap, BarChart3, Bot, Trophy, Settings } from "lucide-react";

function App() {
  return (
    <Routes>
      {/* Guest Layout Shell */}
      <Route element={<GuestLayout />}>
        <Route path="/" element={<Home />} />
        <Route
          path="/login"
          element={
            <PublicRoute>
              <Login />
            </PublicRoute>
          }
        />
        <Route
          path="/register"
          element={
            <PublicRoute>
              <Register />
            </PublicRoute>
          }
        />
      </Route>

      {/* Student Layout Shell */}
      <Route
        path="/student"
        element={
          <ProtectedRoute>
            <StudentLayout />
          </ProtectedRoute>
        }
      >
        <Route path="workspace" element={<Dashboard />} />
        
        {/* Sidebar Placeholder Pages */}
        <Route
          path="practice"
          element={
            <PlaceholderPage
              title="Practice Papers"
              description="Ingest practice question worksheets and navigate solved explanations."
              icon={FileText}
              roadmap={[
                { title: "LaTeX Parser", desc: "Translate raw equations into beautifully rendered LaTeX math symbols." },
                { title: "Solutions Guide", desc: "View detailed solving steps generated by local models." },
              ]}
            />
          }
        />
        <Route
          path="mock-tests"
          element={
            <PlaceholderPage
              title="Mock Tests"
              description="Simulate real competitive online test conditions with custom pacing."
              icon={GraduationCap}
              roadmap={[
                { title: "Exam Simulator", desc: "Standardized timer controls conforming to official test limits." },
                { title: "Auto Grading", desc: "Instant score validation upon test packet submission." },
              ]}
            />
          }
        />
        <Route
          path="analytics"
          element={
            <PlaceholderPage
              title="Performance Analytics"
              description="Analyze accuracy trends, learning pacing, and subject strengths."
              icon={BarChart3}
              roadmap={[
                { title: "Pacing Gauges", desc: "Monitor solved speed metrics per question." },
                { title: "Weakness Reports", desc: "Flag topics needing additional reference practice." },
              ]}
            />
          }
        />
        <Route
          path="mentor"
          element={
            <PlaceholderPage
              title="AI Mentor"
              description="Interact with a virtual companion trained on exam syllabi."
              icon={Bot}
              roadmap={[
                { title: "Syllabus Chatbot", desc: "Ask doubt questions directly on exam modules." },
                { title: "Pacing Tips", desc: "Get feedback on time management habits." },
              ]}
            />
          }
        />
        <Route
          path="achievements"
          element={
            <PlaceholderPage
              title="Achievements"
              description="Unlock milestone trophies by maintaining learning habits."
              icon={Trophy}
              roadmap={[
                { title: "Solve Streaks", desc: "Earn rewards for consecutive practice uploads." },
                { title: "Accuracy Medals", desc: "Unlock badges for achieving high test scores." },
              ]}
            />
          }
        />
        <Route
          path="settings"
          element={
            <PlaceholderPage
              title="Workspace Settings"
              description="Manage study goals, email configurations, and account details."
              icon={Settings}
              roadmap={[
                { title: "Profile Updates", desc: "Configure username and basic candidate preferences." },
                { title: "System Preferences", desc: "Adjust notification timings and visual modes." },
              ]}
            />
          }
        />

        {/* Fallback Workspace 404 Page */}
        <Route path="*" element={<Workspace404 />} />
      </Route>
    </Routes>
  );
}

export default App;